feat: Compile time array bounds check for literal indices (#1448)
@mark-koch , @ss2165 

Regarding issue #1438 , the proposed pull request implements the
ArrayIndexChecker(CustomCallChecker) to determine if a index is out of
bounds.

This contains a new set of tests specifically for checking the index in
various positive and negative ways. If an error is caught and
IndexOutOfBoundsError exception is thrown with more details.

I have also run the full pytest tests was tested with 2 tests failing
with this exception:


Here is the full error message I go while running pytest:

```
guppylang-internals/src/guppylang_internals/std/_internal/checker.py:283: GuppyError
====================================== short test summary info ======================================
FAILED tests/integration/test_quantum.py::test_barrier_array - guppylang_internals.error.GuppyError: ArrayIndexChecker.IndexOutOfBoundsError(span=PlaceNode(pla...
FAILED tests/integration/test_state_result.py::test_array_access - guppylang_internals.error.GuppyError: ArrayIndexChecker.IndexOutOfBoundsError(span=PlaceNode(pla...
================= 2 failed, 1202 passed, 23 skipped, 4 xfailed in 80.99s (0:01:20) ==================
```

**1. tests/integration/test_quantum.py::test_barrier_array**

```
def test_barrier_array(validate):
    """Barrier on array/struct access."""

    @guppy
    @no_type_check
    def test() -> None:
        qs = array(qubit() for _ in range(4))
        q.h(qs[1])
        q.h(qs[2])
        barrier(qs[1], qs[2], qs[3])
        barrier(qs[1])
        q.h(qs[3])

        q.cx(qs[1], qs[2])
        barrier(qs[2], qs[3])
        q.cx(qs[3], qs[4]) #IndexOutOfBoundsError here...
        barrier(qs)
        discard_array(qs)

    validate(test.compile_function())
```
Error:
`guppylang_internals.error.GuppyError:
ArrayIndexChecker.IndexOutOfBoundsError(span=PlaceNode(place=Variable(name='qs',
ty=OpaqueType(args=[TypeArg(ty=OpaqueType(args=[],
defn=OpaqueTypeDef(id=DefId(id=263), name='qubit', defined_at=None,
description='type', params=[], never_copyable=True,
never_droppable=True, to_hugr=<function custom_type.<locals>.<lambda> at
0x705621339d20>, bound=None))),
ConstArg(const=ConstValue(ty=NumericType(kind=<Kind.Nat: 1>),
value=4))], defn=OpaqueTypeDef(id=DefId(id=10), name='array',
defined_at=None, description='type', params=[TypeParam(idx=0, name='T',
must_be_copyable=False, must_be_droppable=False), ConstParam(idx=1,
name='n', ty=NumericType(kind=<Kind.Nat: 1>), from_comptime_arg=False)],
never_copyable=True, never_droppable=False, to_hugr=<function
_array_to_hugr at 0x705660db24b0>, bound=None)),
defined_at=Name(id='qs', ctx=Store()), flags=<InputFlags.NoFlags: 0>,
is_func_input=False)), _parent=None, children=[], index=4, size=4)`



**2. tests/integration/test_state_result.py::test_array_access**

```
def test_array_access(validate):
    @compile_guppy
    def main() -> None:
        qs = array(qubit() for _ in range(4))
        h(qs[1])
        h(qs[2])
        state_result("a", qs[1], qs[2], qs[3])
        state_result("b", qs[1])
        h(qs[3])

        cx(qs[1], qs[2])
        state_result("c", qs[2], qs[3])
        cx(qs[3], qs[4]) #IndexOutOfBoundsError here...
        discard_array(qs)

    validate(main)
```
Error
`guppylang_internals.error.GuppyError:
ArrayIndexChecker.IndexOutOfBoundsError(span=PlaceNode(place=Variable(name='qs',
ty=OpaqueType(args=[TypeArg(ty=OpaqueType(args=[],
defn=OpaqueTypeDef(id=DefId(id=263), name='qubit', defined_at=None,
description='type', params=[], never_copyable=True,
never_droppable=True, to_hugr=<function custom_type.<locals>.<lambda> at
0x7dd26ba35d20>, bound=None))),
ConstArg(const=ConstValue(ty=NumericType(kind=<Kind.Nat: 1>),
value=4))], defn=OpaqueTypeDef(id=DefId(id=10), name='array',
defined_at=None, description='type', params=[TypeParam(idx=0, name='T',
must_be_copyable=False, must_be_droppable=False), ConstParam(idx=1,
name='n', ty=NumericType(kind=<Kind.Nat: 1>), from_comptime_arg=False)],
never_copyable=True, never_droppable=False, to_hugr=<function
_array_to_hugr at 0x7dd2ab4b24b0>, bound=None)),
defined_at=Name(id='qs', ctx=Store()), flags=<InputFlags.NoFlags: 0>,
is_func_input=False)), _parent=None, children=[], index=4, size=4)`

I have modified those 2 unit tests so that they do not fail, but if they
should be modified in some other way, please let me know.

---------

Co-authored-by: Maximilian Rüsch <78490564+maximilianruesch@users.noreply.github.com>
Co-authored-by: Mark Koch <48097969+mark-koch@users.noreply.github.com>
Co-authored-by: nicolaassolini-qntm <nicola.assolini@quantinuum.com>